### ISSUE TITLE
Github repository is latest version? (infused patch for outfitter)

### ISSUE THREAD

**Issue by Gummar** [Killface1980/RW_Outfitter#12]
Hello, Steam says the last update of this mod was on 27 august but the github repository was lastly updated on 2 august, so I don't know if the repository is with the latest version, if it isn't, can you update the github repository to the latest version?

EDIT: I didn't notice I was posting on Outfitter, I wanted to post on [RW_Outfitter_Infused
](https://github.com/Killface1980/RW_Outfitter_Infused) instead, sorry.

**Comment by tommargar** [comment]
just deleted the Infused repo as it wasn't updated. The latest code is now included in the main Outfitter repo. You can output the Infused dll directly to the Outfitter assembly, but there's no current stand alone release except Steam.

**Comment by Gummar** [comment]
Can you do a standalone release out of Steam?

**Comment by tommargar** [comment]
added here https://github.com/Killface1980/RW_Outfitter/releases/tag/0.17.2
