### ISSUE TITLE
Missing battle beacon

### ISSUE THREAD

**Issue by tommargar** [Killface1980/RW_Outfitter#13]
Battle & service beacon as separate download

**Comment by Pichu0102** [comment]
No longer works as of most recent steam workshop release.
https://gist.github.com/HugsLibRecordKeeper/10fec0957dec2c3d79db4f2179d736c0

**Comment by tommargar** [comment]
Updated, current version attached.

The beacon now only scans for apparel within range. You can build multiple beacons to extend the range.
[ServiceBeacons.zip](https://github.com/Killface1980/RW_Outfitter/files/1535580/ServiceBeacons.zip)

**Comment by Pichu0102** [comment]
Seems broken again, sorry.

https://git.io/vhq0K

Edit: Went at the dll with a hex editor since I couldn't figure out Visual Studio very quickly, and changed armorOnly to ArmorOnly. Works now.
