### ISSUE TITLE
Console error and strange in-game behavior

### ISSUE THREAD

**Issue by Crusader2010** [Killface1980/RW_Outfitter#16]
Hello! I'm getting three console errors (see below). The only reference I could find to ManagingSpeed is inside "Outfitter.dll". I'm using Outfitter, Infused and the old version (A17) of the patch for these two. Haven't had any issues until now.

There is also a strange pawn behavior (not sure whether it's related to these errors or not): they keep indefinitely changing the two same clothes. That is, dropping their equipped jacket, then picking up another one (even though it doesn't have a better score than the current one), then picking up the first one again, dropping it, picking up the other, etc. Sometimes it also happens when these two clothes have identical stats.

These console errors seem to occur repeatedly. If needed, I can provide a saved game + archive with all of my mods. Attaching the ModConfig.XML and output_log.txt files.

[ModsConfig.zip](https://github.com/Killface1980/RW_Outfitter/files/1593877/ModsConfig.zip)
[output_log - Copy.zip](https://github.com/Killface1980/RW_Outfitter/files/1593881/output_log.-.Copy.zip)

> Failed to find RimWorld.StatDef named ManagingSpeed. There are 101 defs of this type loaded.
Verse.Log:Error(String)
Verse.DefDatabase`1:GetNamed(String, Boolean)
Outfitter.ApparelStatsHelper:GetWeightedApparelStats(Pawn)
Outfitter.ApparelStatCache:get_StatCache()
Outfitter.ApparelStatCache:GetStatsOfApparelInfused(Apparel, HashSet`1&)
Outfitter.ApparelStatCache:GetAllOffsets(Apparel)
Outfitter.ApparelStatCache:ApparelScoreRaw(Apparel)
Outfitter.JobGiver_OutfitterOptimizeApparel:TryGiveJob_Prefix(Job&, Pawn)
RimWorld.JobGiver_OptimizeApparel:TryGiveJob_Patch1(Object, Pawn)
Verse.AI.ThinkNode_JobGiver:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob_Patch1(Object, ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:CheckForJobOverride()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

> Failed to find RimWorld.StatDef named ManagingSpeed. There are 101 defs of this type loaded.
Verse.Log:Error(String)
Verse.DefDatabase`1:GetNamed(String, Boolean)
Outfitter.ApparelStatsHelper:GetWeightedApparelStats(Pawn)
Outfitter.ApparelStatCache:get_StatCache()
Outfitter.ApparelStatCache:ApparelScoreRaw(Apparel)
Outfitter.JobGiver_OutfitterOptimizeApparel:TryGiveJob_Prefix(Job&, Pawn)
RimWorld.JobGiver_OptimizeApparel:TryGiveJob_Patch1(Object, Pawn)
Verse.AI.ThinkNode_JobGiver:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob_Patch1(Object, ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob_Patch1(Object, JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

> Failed to find RimWorld.StatDef named ManagingSpeed. There are 101 defs of this type loaded.
Verse.Log:Error(String)
Verse.DefDatabase`1:GetNamed(String, Boolean)
Outfitter.ApparelStatsHelper:GetWeightedApparelStats(Pawn)
Outfitter.ApparelStatCache:get_StatCache()
Outfitter.ITab_Pawn_Outfitter:DrawApparelStats(Vector2, Rect)
Outfitter.ITab_Pawn_Outfitter:FillTab()
Verse.<DoTabGUI>c__AnonStorey0:<>m__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by tommargar** [comment]
I've updated, the ManagingSpeed comes from Fluffy's mod, but shouldn't be called if it's not there.
The cloth swapping should also be fixed. I'll leave this issue open for now.

**Comment by Crusader2010** [comment]
Thank you for the quick fix. I'll try the new version as soon as possible and let you know if it happens again. What's strange is that the code for ManagingSpeed from the source code of the mod was commented out when I looked, with no other references.

Also, is the patch for Infused included in Outfitter.dll (I saw the second project in the solution)?

**Comment by tommargar** [comment]
I've removed the ManagingSpeed, as there are no clothes which modify the stat and the stat is rather useless.
Outfitter Infused is only invoked from Outfitter, bugs when Infused is not active. Had to keep it separate.

**Comment by Crusader2010** [comment]
Update: the "ManagingSpeed" error is definitely gone. For now I've not been experiencing any more infinite loops with changing gear.
